classdef NMC111 < ActiveMaterial
    
    methods

        function model = NMC111(paramobj)
            
            model = model@ActiveMaterial(paramobj);
            
        end
        
        function state = updateOCP(model, state)
        % Calculate the equilibrium open cirucuit potential of nmc111 according to the model used by Torchio et al [1].

        % Calculate the lithiation of the active material. This is a simplification for the initial code! The "real" value of
        % theta should be calculated using the surface concentration of Li and the maximum lithium concentration:
        %

            refT = 298.15;  % [K]

            T = state.T;
            c = state.cElectrode;
            
            theta = c ./ model.Li.cmax;
            % model.theta = (model.theta0 - model.theta100) .* model.SOC + model.theta100;
            
            % Calculate the open-circuit potential at the reference temperature for the given lithiation
                    
            coeff1_refOCP = [ -4.656   , ...
                              0        , ...
                              + 88.669 , ...
                              0        , ...
                              - 401.119, ...
                              0        , ...
                              + 342.909, ...
                              0        , ...
                              - 462.471, ...
                              0        , ...
                              + 433.434];
            
            coeff2_refOCP =[ -1      , ...
                             0       , ...
                             + 18.933, ...
                             0       , ...
                             - 79.532, ...
                             0       , ...
                             + 37.311, ...
                             0       , ...
                             - 73.083, ...
                             0       , ...
                             + 95.960];
            
            refOCP = polyval(coeff1_refOCP(end:-1:1),theta)./ polyval(coeff2_refOCP(end:-1:1),theta);    
                    
            % Calculate the entropy change at the given lithiation
            
            coeff1_dUdT = [0.199521039        , ...
                           - 0.928373822      , ...
                           + 1.364550689000003, ...
                           - 0.611544893999998];
            
            coeff2_dUdT = [1                  , ...
                           - 5.661479886999997, ...
                           + 11.47636191      , ... 
                           - 9.82431213599998 , ...
                           + 3.048755063];
            
            dUdT = -1e-3.*polyval(coeff1_dUdT(end:-1:1),theta)./ polyval(coeff2_dUdT(end:-1:1),theta);
            
            % Calculate the open-circuit potential of the active material
            OCP = refOCP + (T - refT) .* dUdT;

            state.OCP = OCP;
            
        end
        
    end
end

%% References
%   [1] Torchio et al, Journal of The Electrochemical Society, 163 (7)
%   A1192-A1205 (2016), DOI: 10.1149/2.0291607jes

