classdef PEMgridGenerator2D < PEMgridGenerator


    properties

        % Length in x and y directions
        xlength
        ylength

        % Discretization numbers in x and y directions
        Nx      
        Ny
        
    end
    
    methods

        function gen = PEMgridGenerator2D()
            
            gen = gen@PEMgridGenerator();
            
        end

        function [inputparams, gen] = updateInputParams(gen, inputparams, params)

            inputparams = gen.setupInputParams(inputparams, []);
            
        end

        function [inputparams, gen] = setupGrid(gen, inputparams, params)
            
            G = cartGrid([gen.Nx, gen.Ny], [gen.xlength, gen.ylength]);

            parentGrid = Grid(G);
            
            G = genSubGrid(parentGrid, (1 : parentGrid.getNumberOfCells())');
            
            inputparams.G = G;
            gen.parentGrid = parentGrid;
            
        end
        
        function inputparams = setupElectrolyte(gen, inputparams, params)
        % Method that setups the grid and the coupling for the electrolyte model

            ncells = gen.parentGrid.getNumberOfCells();
            params.cellind = (1 : ncells)';
            inputparams = setupElectrolyte@PEMgridGenerator(gen, inputparams, params);
            
        end

        function inputparams = setupElectrodeElectrolyteCoupTerm(gen, inputparams, params)

            an    = 'Anode';
            ct    = 'Cathode';
            elyte = 'Electrolyte';
            
            Nx = gen.Nx;
            Ny = gen.Ny;

            % The following setup is correct but not very robust as it assumes knowledge of the cartesian structure of
            % the grid generated by cartGrid.
            
            params.(an).couplingcells = 1 + Nx*(0 : (Ny - 1))';
            params.(an).couplingfaces = 1 + (Nx + 1)*(0 : (Ny - 1))';
            params.(ct).couplingcells = Nx + Nx*(0 : (Ny - 1))';
            params.(ct).couplingfaces = (Nx + 1) + (Nx + 1)*(0 : (Ny - 1))';

            inputparams = setupElectrodeElectrolyteCoupTerm@PEMgridGenerator(gen, inputparams, params);
            
        end

        
    end
    
    
end
