setupoutput = false;
if setupoutput
    ind = cellfun(@(state) ~isempty(state), states);
    states = states(ind);
    for istate = 1 : numel(states)
        states{istate} = model.addVariables(states{istate});
    end
end

time = cellfun(@(state) state.time, states);
E = cellfun(@(state) state.(oer).(ptl).E, states);
I = cellfun(@(state) state.(oer).(ctl).I, states);

% load results from old code

close all

figure
plot(time/hour, E)
xlabel('time [hour]');
ylabel('voltage');

figure
plot(time/hour, -I)
xlabel('time [hour]');
ylabel('Current [A]');

fds = {'OxygenEvolutionElectrode.T', ...
       'OxygenEvolutionElectrode.ExchangeLayer.T', ...
       'OxygenEvolutionElectrode.CatalystLayer.T', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.O2rhoeps', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.liquidAccumTerm', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.E', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.compGasMasses{2}', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.liqrhoeps', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.liqeps', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.volumeFractions{3}', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.volumeFractions{2}', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.volumeFractions{1}', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.liqrho', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.H2Ogasrhoeps', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.compGasMasses{1}', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.OHceps', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.OHaccum', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.compGasAccums{2}', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.compGasAccums{1}', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.concentrations{2}', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.diffOHFlux', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.OHmolality', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.concentrations{3}', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.concentrations{1}', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.liquidStateEquation', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.jBcSource', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.phi', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.T', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.vaporPressure', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.viscosities{2}', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.viscosities{1}', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.H2Oa', ...
       'OxygenEvolutionElectrode.PorousTransportLayer.compGasPressures{2}'};


for ifd = 1 : numel(fds)
    fd = fds{ifd};
    [ymin, ymax, y] = getvals(fd, states);
    figure
    hold on
    plot(time, ymin);
    plot(time, ymax);
    str = strrep(fd, 'OxygenEvolutionElectrode.PorousTransportLayer', '');
    title(str)
end

    
