MRST
====

BattMo is based on the open-source sofware MRST.

.. image:: img/mrst.png
   :target: `MRSTwebpage`_
      
`MRSTwebpage`_ is primarly dedicated to reservoir modelling and simulation and has been developed essentially by the
`Computational Geosciences group
<https://www.sintef.no/en/digital/departments-new/applied-mathematics/computational-geoscience/>`_ in the `Department of
Mathematics and Cybernetics at SINTEF Digital
<https://www.sintef.no/en/digital/departments-new/applied-mathematics/>`_. The software contains generic functionalities such as

* Discrete differential operators,
* Automatic Differentiation support,
* Newton solver API for easy integration of new set of equations and variables.

which BattMo relies heavily on.
  
On the `MRSTwebpage`_ webpage, you can find `documentations <https://www.sintef.no/projectweb/mrst/documentation/>`_ and
`tutorials <https://www.sintef.no/projectweb/mrst/documentation/tutorials/>`_.

We recommend the following tutorials which deal with grid visualization and grid generation will be usefull for BattMo
users.

.. _visualization:

`Visualization Tutorial <https://www.sintef.no/projectweb/mrst/documentation/tutorials/visualization-tutorial/>`_
-----------------------------------------------------------------------------------------------------------------

   .. image:: img/gridviz.png
   
`Grid Factory Tutorial <https://www.sintef.no/projectweb/mrst/documentation/tutorials/grid-factory-tutorial/>`_
---------------------------------------------------------------------------------------------------------------

   .. image:: img/gridfact.png


see :ref:`here<visualization>`.              
              
.. _MRSTwebpage: https://www.sintef.no/Projectweb/MRSTwebpage/

