(defun battmodoc-build ()
  (interactive)
  (let ((outputbuffer (get-buffer-create "*buildoutput*"))
        (default-directory "/home/xavier/Matlab/Projects/battmo/Documentation/"))
    (pop-to-buffer outputbuffer)
    (erase-buffer)
    (start-process "battmo-build" outputbuffer "make" "html")
    )
  )

(defun battmodoc-build-examples ()
  (interactive)
  (let ((outputbuffer (get-buffer-create "*publishoutput*"))
        (directory "/home/xavier/Matlab/Projects/battmo/Documentation/utils/"))
    (pop-to-buffer outputbuffer)
    (erase-buffer)
    (start-process "battmo-publish" outputbuffer "python" (concat directory "buildPublishedExamples.py"))
    )
  )

(defun battmodoc-publish ()
  (interactive)
  (let ((default-directory "/home/xavier/Matlab/Projects/battmo/Documentation/"))
    (shell-command "cp -rf _build/html/* /home/xavier/Matlab/Projects/battmo-doc-test/" )
    )
  (let ((default-directory "/home/xavier/Matlab/Projects/battmo-doc-test/"))
    (shell-command "git add *" )
    (shell-command "git commit -m \"update in doc\"")
    (shell-command "git push -f" )
    )  
  )

(defun convert-to-attribute ()
  (interactive)
  (re-search-forward (rx (group (1+ (any word))) (0+ space) "%" (0+ space) (group (0+ nonl))))
  (let ((att (match-string 1))
        (com (match-string 2))
        )
    (beginning-of-line)
    (kill-line)
    (insert "   .. attribute:: " att "\n\n")
    (insert "      " com "\n")
    )
  )

