name: "Sphinx: Render docs"

on: 
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Install LaTeX and dvipng
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive texlive-latex-extra dvipng
    - name: Add LaTeX and dvipng directories to PATH
      run: |
        echo "export PATH=/usr/bin:$PATH" >> $GITHUB_ENV  
    - name: Print PATH
      run: echo $PATH
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "Documentation/"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentationHTML
        path: Documentation/_build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Documentation/_build/html

