name: "Sphinx: Render docs"

on: 
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Install LaTeX and dvipng
      run: |
        mkdir -p $HOME/texlive
        wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
        tar -xzf install-tl-unx.tar.gz --strip-components=1 -C $HOME/texlive
        echo "selected_scheme scheme-full" >> texlive.profile
        $HOME/texlive/install-tl --profile=texlive.profile
        export PATH="$HOME/texlive/bin/x86_64-linux:$PATH"
        tlmgr install collection-latexrecommended
        sudo apt-get update
        sudo apt-get install -y dvipng

    - name: Check LaTeX and dvipng versions
      run: |
        latex --version
        dvipng --version
    - name: Check LaTeX and dvipng permissions
      run: |
        ls -l $(which latex)
        ls -ld $(dirname $(which latex))
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "Documentation/"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentationHTML
        path: Documentation/_build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Documentation/_build/html

