name: "Sphinx: Render docs"

on: 
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Install TeX Live and LaTeX packages
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive texlive-latex-extra dvipng

    - name: Check LaTeX and dvipng versions
      run: |
        latex --version
        dvipng --version
    - name: Check LaTeX and dvipng permissions
      run: |
        ls -l $(which latex)
        ls -ld $(dirname $(which latex))
    - name: Add LaTeX and dvipng directories to PATH
      run: |
        echo "PATH=$PATH:/usr/local/texlive/" >> $GITHUB_ENV
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "Documentation/"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentationHTML
        path: Documentation/_build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Documentation/_build/html

