name: "Sphinx: Render docs"

on: 
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    env:
      imgmath_latex: "/home/runner/work/_temp/setup-texlive-action/2024/bin/x86_64-linux/latex"

    steps:
    - uses: actions/checkout@v4
    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: scheme-basic  # Or choose the appropriate package scheme
        cache: false
    
    - name: Update symbolic link for LaTeX
      run: ln -sf /home/runner/work/_temp/setup-texlive-action/2024/bin/x86_64-linux/latex $(which latex)
    - name: Check LaTeX permissions
      run: |
        ls -l $(which latex)
        ls -ld $(dirname $(which latex))
    - name: Add LaTeX and dvipng directories to PATH
      run: |
        echo "PATH=$PATH:/home/runner/work/_temp/setup-texlive-action/2024/bin/x86_64-linux" >> $GITHUB_ENV
    - name: Print PATH
      run: echo $PATH  
    - name: Replace placeholder with actual path in conf.py
      run: sed -i "s|imgmath_latex = 'latex'|imgmath_latex = '/home/runner/work/_temp/setup-texlive-action/2024/bin/x86_64-linux/latex'|g" Documentation/conf.py
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "Documentation/"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentationHTML
        path: Documentation/_build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Documentation/_build/html

