name: "Sphinx: Render docs"

on: 
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Install expect
      run: sudo apt-get update && sudo apt-get install -y expect
    - name: Install LaTeX
      run: |
        mkdir -p $HOME/.local/texlive
        echo "export TEXLIVE_INSTALL_PREFIX=$HOME/.local/texlive" >> $GITHUB_ENV
        echo "export TEXLIVE_INSTALL_TEXDIR=$HOME/.local/texlive/2014" >> $GITHUB_ENV
        wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
        tar -xzf install-tl-unx.tar.gz --strip-components=1 -C $HOME/.local/texlive
        cd $HOME/.local/texlive
        expect -c '
          spawn ./install-tl
          expect "Choose the directory for installation"
          send "D\n"
          expect "Enter command:"
          send "I\n"
          expect eof
        '
        export PATH="$HOME/.local/texlive/bin/x86_64-linux:$PATH"
        tlmgr install collection-latexrecommended 
       

    - name: Verify LaTeX installation
      run: |
        latex --version
        kpsewhich -var-value=TEXMFROOT
    - name: Check LaTeX and dvipng permissions
      run: |
        ls -l $(which latex)
        ls -ld $(dirname $(which latex))
    - name: Add LaTeX and dvipng directories to PATH
      run: |
        echo "PATH=$PATH:/usr/local/texlive/" >> $GITHUB_ENV
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "Documentation/"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentationHTML
        path: Documentation/_build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Documentation/_build/html

