name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        publish: false
        documentation_path: ./Documentation
        requirements_path: ./Documentation/requirements.txt
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}    


