# See https://github.com/matlab-actions/overview for more information
name: test a function

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ test ]
    
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          lfs: true

      # Use the submodules' remote-tracking branches
      - name: Update submodules
        run: git submodule update --init

      - name: Start virtual display server
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
            
      # Set up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b

      # Execute the tests
      - name: Running some tests
        uses: matlab-actions/run-command@v2
        with:
          command: run('runTest.m')
